export const Types = {
  FILTERS_DATA_REQUEST: '@filters/FILTERS_DATA_REQUEST',
  FILTERS_DATA_REQUEST_ERROR: '@filters/FILTERS_DATA_REQUEST_ERROR',
  FILTERS_DATA_REQUEST_SUCCESS: '@filters/FILTERS_DATA_REQUEST_SUCCESS',
};
